### ISSUE TITLE
Add "ReversePP" API

### ISSUE THREAD

**Issue by dfaram7** [APIs-guru/openapi-directory#1140]
**Format**: OpenAPI 2.0 (fka Swagger)
**Official**: YES
**Url**: https://dev.reversepp.com/swagger.json
**Name**: ReversePP
**Category**: open_data
**Logo**: https://lh3.googleusercontent.com/FgmxE0k87WHz0WdUX-abBHpDqJ9fk9fwJcn8N3XYfnyTXxPLrZBs29XKAKWpYVp9qyx5tM8vb7eIZJU0cBndyx99pg=w128-h128-e365-rj-sc0x00ffffff

**Comment by MikeRalphson** [comment]
@dfaram7 - It looks like your API definition did not fully validate. Please mention (@) MikeRalphson to discuss. Here is the log output:

**Comment by MikeRalphson** [comment]
npm WARN cli npm v9.5.1 does not support Node.js v16.10.0. You should probably upgrade to a
npm WARN cli newer version of node as we can't make any promises that npm will work with this
npm WARN cli version. This version of npm supports the following node versions: `^14.17.0 ||
npm WARN cli ^16.13.0 || >=18.0.0`. You can find the latest version at https://nodejs.org/.

> openapi-directory@2.0.0 check
> node --no-warnings --insecure-http-parser ./node_modules/@Mermade/api-registry/registry.js check https://dev.reversepp.com/swagger.json

/Users/mikeralphson/node/api-registry/commands.js:60
const resOpt = { resolve: true, fatal: true, verbose: false, cache: oasCache, fetch:fetch, agent: bobwAgent, fetchOptions: { cacheFolder: mainCache, refresh: 'default' } };
                                                                                    ^

ReferenceError: fetch is not defined
    at Object.<anonymous> (/Users/mikeralphson/node/api-registry/commands.js:60:85)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/mikeralphson/node/api-registry/registry.js:8:13)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at node:internal/main/run_main_module:17:47

**Comment by MikeRalphson** [comment]
Automated checks succeeded.

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! The API will be live on the website after the next CI run.
